# Generated by Django 5.2.8 on 2025-11-28 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_autor',
            fields=[
                ('id_autor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_editora',
            fields=[
                ('id_editora', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_motivo_remocao',
            fields=[
                ('id_motivo', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_status_livro',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_livro',
            fields=[
                ('id_livro', models.AutoField(primary_key=True, serialize=False)),
                ('isbn', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('ano_publicacao', models.IntegerField()),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('dt_atualizacao', models.DateTimeField(auto_now=True)),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='biblioteca.tbl_editora')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_livro_autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.tbl_autor')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.tbl_livro')),
            ],
            options={
                'unique_together': {('livro', 'autor')},
            },
        ),
        migrations.AddField(
            model_name='tbl_livro',
            name='autores',
            field=models.ManyToManyField(through='biblioteca.tbl_livro_autor', to='biblioteca.tbl_autor'),
        ),
        migrations.CreateModel(
            name='tbl_livro_categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.tbl_categoria')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.tbl_livro')),
            ],
            options={
                'unique_together': {('livro', 'categoria')},
            },
        ),
        migrations.AddField(
            model_name='tbl_livro',
            name='categorias',
            field=models.ManyToManyField(through='biblioteca.tbl_livro_categoria', to='biblioteca.tbl_categoria'),
        ),
        migrations.AddField(
            model_name='tbl_livro',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='biblioteca.tbl_status_livro'),
        ),
        migrations.CreateModel(
            name='tbl_livro_remocao',
            fields=[
                ('id_remocao', models.AutoField(primary_key=True, serialize=False)),
                ('dt_remocao', models.DateTimeField(auto_now_add=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='biblioteca.tbl_livro')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='biblioteca.tbl_motivo_remocao')),
                ('removido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='biblioteca.tbl_usuario')),
            ],
        ),
    ]
