# Generated by Django 5.2.8 on 2025-11-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_usuario',
            name='sobrenome',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
