# Generated by Django 5.2.8 on 2025-12-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_tbl_livro_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_livro',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
