# Generated by Django 5.2.8 on 2025-12-10 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_aluno_emprestimo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_autor',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='tbl_categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='tbl_editora',
            options={'verbose_name': 'Editora', 'verbose_name_plural': 'Editoras'},
        ),
    ]
