# Generated by Django 5.2.8 on 2025-12-10 03:45

import biblioteca.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0008_alter_tbl_autor_options_alter_tbl_categoria_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'verbose_name': 'Empréstimo', 'verbose_name_plural': 'Empréstimos'},
        ),
        migrations.AlterModelOptions(
            name='tbl_livro_remocao',
            options={'verbose_name': 'Remoção de Livro', 'verbose_name_plural': 'Remoções de Livros'},
        ),
        migrations.AlterModelOptions(
            name='tbl_motivo_remocao',
            options={'verbose_name': 'Motivo de Remoção', 'verbose_name_plural': 'Motivos de Remoção'},
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tbl_livro',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to=biblioteca.models.livro_capa_upload_path),
        ),
        migrations.AlterField(
            model_name='tbl_status_livro',
            name='descricao',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterModelTable(
            name='tbl_autor',
            table='tbl_autor',
        ),
        migrations.AlterModelTable(
            name='tbl_categoria',
            table='tbl_categoria',
        ),
        migrations.AlterModelTable(
            name='tbl_editora',
            table='tbl_editora',
        ),
        migrations.AlterModelTable(
            name='tbl_livro_autor',
            table='tbl_livro_autor',
        ),
        migrations.AlterModelTable(
            name='tbl_livro_categoria',
            table='tbl_livro_categoria',
        ),
        migrations.AlterModelTable(
            name='tbl_livro_remocao',
            table='tbl_livro_remocao',
        ),
        migrations.AlterModelTable(
            name='tbl_motivo_remocao',
            table='tbl_motivo_remocao',
        ),
    ]
