# Generated by Django 5.2.8 on 2025-12-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0009_alter_emprestimo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_livro',
            name='disponivel',
            field=models.IntegerField(default=0),
        ),
    ]
